
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/COVID_DATA_V3
    hikari:
      driver-class-name: org.postgresql.Driver
      username: postgres
      password: 123456
      pool-name: SpringBootHikariCP # HikariCP
      maximum-pool-size: 100
      minimum-idle: 5
      max-lifetime: 300000
      connection-timeout: 300000
      initialization-fail-timeout: 0
    dbcp2:
      pool-prepared-statements: true
    username: postgres
    password: 123456

  # JPA Configuration
  jpa:
    properties:
      org:
        hibernate:
          envers:
            default_schema: audit
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQL95Dialect
    hibernate:
      ddl-auto: update
  jackson:
    property-naming-strategy: com.fasterxml.jackson.databind.PropertyNamingStrategy.LowerCaseWithUnderscoresStrategy

server:
  port: 8082
